# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f609bb086bd11d07993f34c4a6d237dc92db50ca5493a2b220d526777c486eca300ab69f530fc84faebc0014c65ef9eb91883b5c5411013f0700cc541358e911

test:
  secret_key_base: 4f8d4428d91d6f958c8d41751b5b1f4d709c212ffdbdbdf4e9fd2761d19d44348953e729f7051d61e5a15d3c35902e85a5ca2f7ac2cc6bcb0ffd031515211e89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
